name: Reproduce Job Logs

on:
  workflow_dispatch:

jobs:
  reproduce-log:
    runs-on: ubicloud-standard-4

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Update and install dependencies
      run: |
        sudo apt-get remove -y containerd
        sudo apt-get remove -y docker.io
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev python3-venv

    - name: Set up and activate virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install types-toml types-PyYAML tomli toml sqlparse scipy responses pytest-xdist pytest-socket pytest-env pytest-cov pytest pydot pluggy Pillow mock matplotlib kiwisolver iniconfig fonttools execnet exceptiongroup cycler coverage contourpy attrs
